name: Container Image CI
on: [push]
jobs:
  build:
    name: Compliance Build Workflow
    runs-on: ubuntu-latest
    env:
      GHCR: ghcr.io
      IMAGE_NAME: example-node-webapp
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Scan current project directory with Grype
      id: scan_directory
      uses: anchore/scan-action@v2
      with:
        path: "./"
        fail-build: true
        acs-report-enable: true
        severity-cutoff: critical

    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan_directory.outputs.sarif }}
    
    - name: Build image from Dockerfile
      id: build_image
      run: |
        docker build . \
          --tag="localbuild/$IMAGE_NAME:latest" \
          --tag="$GHCR/$GITHUB_ACTOR/$IMAGE_NAME:latest" \
          --tag="$GHCR/$GITHUB_ACTOR/$IMAGE_NAME:$GITHUB_SHA" \
          --label="org.opencontainers.image.created=$(date +%Y-%m-%d)" \
          --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
          --label="org.opencontainers.image.revision=$GITHUB_SHA" \
          --label="anchore.stig.profile1=redhat-enterprise-linux-7-stig-baseline"
    
    - name: Inspect image 
      id: inspect_image
      run: docker inspect localbuild/$IMAGE_NAME:latest

    - name: Scan built image with Grype
      id: scan_image
      uses: anchore/scan-action@v2
      with:
        image: "localbuild/example-node-webapp:latest"
        fail-build: false
        severity-cutoff: critical

    - name: Login to GitHub Container Registry
      id: ghcr_login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Push image to GitHub Container Registry
      id: ghcr_push
      run: |
        docker push "ghcr.io/${GITHUB_ACTOR}/${IMAGE_NAME}:latest"
        docker push "ghcr.io/${GITHUB_ACTOR}/${IMAGE_NAME}:${GITHUB_SHA}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out deployment code
      uses: actions/checkout@v2
      with:
        repository: 'valancej/compliance-deployment'

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Update Kubernetes resources
      run: |
        cd kustomize/base
        kustomize edit set image example-webapp=ghcr.io/jvalance/example-webapp:$GITHUB_SHA
        cat kustomization.yaml
        kustomize build

    - name: Commit files
      run: |
        git config --local user.email "valancejeremy@gmail.com"
        git config --local user.name "valancej"
        git commit -m "Add changes" -a
  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: valancej/compliance-deployment