name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Anchore scan directory
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Scan current project directory with Grype
      id: scan_directory
      uses: anchore/scan-action@v2
      with:
        path: "./"
        fail-build: true
        acs-report-enable: true
        severity-cutoff: critical

    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan_directory.outputs.sarif }}
    
    - name: Build image from Dockerfile
      id: build_image
      run: docker build -t localbuild/example-node-web-app:latest .
    
    - name: Scan built image with Grype
      id: scan_image
      uses: anchore/scan-action@v2
      with:
        image: "localbuild/example-node-web-app:latest"
        fail-build: true
        severity-cutoff: critical
